### ISSUE TITLE
Possible to set availability time based on the room instead of the building?

### ISSUE THREAD

**Issue by miniaturekites** [cul-it/signage#155]
Hi Nick, I hope this is an okay avenue to request this feature. Olin 104 is only reservable after 5pm, but I didn't realize the sign is pulling availability from the building hours, so it's showing as "available" beginning at 8am, which is misleading. Is it possible to have the availability times on the sign based on the specific room/space availability?

**Comment by cappadona** [comment]
Hey @miniaturekites. In my humble opinion, this is the perfect avenue...I appreciate it 😃.

Each sign is configured to lookup the hours for a library or department as defined in LibCal's hours module to determine whether the spaces represented on the sign are open or closed.

At the moment, the Olin 104 sign defaults to Olin library hours, but the app supports overriding the default via a configuration file. Quickly reviewing the [dept hours currently defined for Olin](https://www.library.cornell.edu/libraries/olin) I'm not seeing anything that aligns with a 5pm opening (at least not today).

Are you able to add another dept in LibCal with hours for Room 104? To be clear, going this route will result in the sign listing the room as **Closed** until 5pm. If you're looking for different behavior, please share so that we can work through the details of this potential new feature request.

Thanks.

**Comment by miniaturekites** [comment]
Having it display "Closed" until 5pm is ideal. Is adding a "department" the only option? I'm concerned that adding a department would display on the public hours page you linked and cause confusion. Is there a way to suppress the display of departments on the website?

**Comment by cappadona** [comment]
Great question re: suppressing hours on the CUL website. We do exactly that for Mann, but I believe `library.cornell.edu` renders the hours verbatim as delivered by the LibCal Hours widget.

I'm saying this mostly based on comparing the [Mann site hours](https://mannlib.cornell.edu/hours) to [Mann hours on CUL site](https://www.library.cornell.edu/libraries/mann).

I'm more familiar with the Mann site since I help manage it, but you can check in with the CUL site team to confirm whether it's possible to suppress dept hours.

**Comment by miniaturekites** [comment]
I made a new "department" (as far as I can tell): https://spaces.library.cornell.edu/admin_hours_location.php?lid=11395

**Comment by cappadona** [comment]
🛎 [Order up!](https://signage-stg-pr-156.herokuapp.com/olin/spaces/room104)

**Comment by cappadona** [comment]
Now [live in production](https://signage.library.cornell.edu/olin/spaces/room104)
